apiVersion: v1
kind: Service
metadata:
  name: cka-redis
  labels:
    app: cka-redis
spec:
  type: ClusterIP
  selector:
    app: cka-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
