apiVersion: v1
kind: ConfigMap
metadata:
  name: cka-api-config
  labels:
    app: cka-api
data:
  CKA_HTTPS_ENABLED: "true"
  CKA_CORS_ORIGINS: "https://intranet.bank.corp"
  CKA_LLM_PROVIDER: "HF"
  CKA_QDRANT_URL: "http://cka-qdrant:6333"
  CKA_USE_QDRANT: "true"
  CKA_USE_REDIS: "true"
