apiVersion: apps/v1
kind: Deployment
metadata:
  name: cka-qdrant
  labels:
    app: cka-qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cka-qdrant
  template:
    metadata:
      labels:
        app: cka-qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:latest
          ports:
            - containerPort: 6333
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
      volumes:
        - name: qdrant-storage
          emptyDir: {}
