apiVersion: v1
kind: Service
metadata:
  name: cka-qdrant
  labels:
    app: cka-qdrant
spec:
  type: ClusterIP
  selector:
    app: cka-qdrant
  ports:
    - name: http
      port: 6333
      targetPort: 6333
