apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cka-api-egress
spec:
  podSelector:
    matchLabels:
      app: cka-api
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: cka-qdrant
        - podSelector:
            matchLabels:
              app: cka-redis
      ports:
        - protocol: TCP
          port: 6333
        - protocol: TCP
          port: 6379
